### PR TITLE
fix : fix youtube display size

### LINKED ISSUE #20: fix: fix youtube video size

### PR DESCRIPTION
**Pull request by Amtsal99**

### CODE REVIEW

File: src/app/youtube/page.tsx [hunk 1]
```diff
@@ -4,7 +4,7 @@ import { FaYoutube } from "react-icons/fa";
 
 export default function Youtube() {
   return (
-    <div className="h-full min-h-screen flex items-center justify-center bg-blue-100">
+    <div className="px-6 h-full min-h-screen flex items-center justify-center bg-blue-100">
```
Comment (chowjustin) [inline src/app/youtube/page.tsx]: tambahin 'overflow-hidden'

**Review by chowjustin — CHANGES_REQUESTED** [review]

**Review by chowjustin — APPROVED** [review]
